apiVersion: v1
kind: Pod
metadata:
  name: ttms # pod name
  labels:
    app: ttms # pod label
spec:
  containers:
    - name: ttms
      image: princeram/timetable:latest
      ports:
        - containerPort: 80
      env:
        - name: HOST
          value: timetable.cioc56gyzvic.ap-south-1.rds.amazonaws.com
        - name: USER
          value: admin
        - name: PASSWORD
          value: Ram12345
        - name: DB
          value: timetable
